FROM python:3.11.3-slim-bullseye

ARG VERSION=0.5.0

RUN  apt-get update -y && \
     apt-get upgrade -y && \
     apt-get dist-upgrade -y && \
     apt-get install -y git && \
     apt-get install -y curl

ENV PYTHONFAULTHANDLER=1 \
  PYTHONUNBUFFERED=1 \
  PYTHONHASHSEED=random \
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_PIP_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100 \
  # Poetry's configuration:
  POETRY_NO_INTERACTION=1 \
  POETRY_VIRTUALENVS_CREATE=false \
  POETRY_CACHE_DIR='/var/cache/pypoetry' \
  POETRY_HOME='/usr/local'\
  POETRY_VERSION=1.7.1

RUN apt-get update
RUN apt-get install -y git
RUN curl -sSL https://install.python-poetry.org | python3 -

RUN useradd -ms /bin/bash dans

WORKDIR /home/dans/acp
COPY pyproject.toml /home/dans/acp/
RUN poetry install --no-root

USER dans
ENV PYTHONPATH=/home/dans/acp/src
ENV BASE_DIR=/home/dans/acp

WORKDIR /home/dans/acp
#CMD ["python", "main.py"]
#CMD ["tail", "-f", "/dev/null"]