[default]
#FastAPI
fastapi_title = "packaging-service"
fastapi_description = "This service supports .."


resources_path = "@format {env[BASE_DIR]}/resources/linkset"

log_file = "@format {env[BASE_DIR]}/logs/ps.log"
#log_file = "../logs/ps.log"
log_level = 10
log_format = "%(asctime)s %(levelname)s %(name)s %(threadName)s : %(message)s"

dans_formats_url = "https://raw.githubusercontent.com/ekoi/DANS-File-Formats/draft/dans-file-formats.json"